"""Async internal L2-plus client: local DB -> MCP retrieval -> L2 generation."""

from __future__ import annotations

import asyncio
from typing import Any

from app import engine


class L2PlusClient:
    """Drop-in replacement for ``LunitClient`` used by chat strategies.

    Planning and retrieval may use orchestration, but ``engine.answer`` guarantees
    that the user-facing draft is generated by L2.
    """

    def __init__(
        self,
        *,
        base_url: str,
        api_key: str | None,
        model: str,
        timeout: float,
        client: engine.L2Client | None = None,
        planner: engine.L2Client | None | object = ...,
    ) -> None:
        self.client = client or engine.L2Client(
            base=base_url, key=api_key, model=model, timeout=timeout
        )
        self.planner = (
            engine.planner_from_env(self.client) if planner is ... else planner
        )

    async def complete(
        self, messages: list[dict[str, Any]], *, max_tokens: int | None = None
    ) -> str:
        output = await asyncio.to_thread(
            engine.answer,
            self.client,
            messages,
            max_tokens=max_tokens,
            planner=self.planner,
            local_first=True,
        )
        return output["answer"]
